server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/uni_docs"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL:abc}
    password: ${PASSWORD:12}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

open:
  api:
    title: API document
    version: v1.0.0
    description: Mo ta
    serverUrl: http://localhost:8080
    serverName: server