server:
  port: 8080
  servlet:
    context-path: /
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: "jdbc:mysql://localhost:3306/uni_docs"
    username: ${DATASOURCE_NAME:root}
    password: ${DATASOURCE_PASS:123456}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL:abc}
    password: ${PASSWORD:12}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

open:
  api:
    title: API document
    version: v1.0.0
    description: Mo ta
    serverUrl: http://localhost:8080
    serverName: server
#duong dan luu file
external:
  upload:
    dir: D:\lt_android\project_nhom\externalUploads
#thanh toan vnpay
payment:
  vnpay:
    tmnCode: ${VNP_TMNCODE:12}
    secretKey: ${VNP_SECRETKEY:12}
    returnUrl: ${VNP_RETURNURL:http://10.0.2.2:8080/api/payment/vn-pay-callback}